services:
  - type: web
    name: crash-delta-md
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBERS
        sync: false
    healthCheckPath: /health
    autoDeploy: true
